#!/usr/bin/env bash
# Installing nginx on server

find="^\tlocation / {"
replace301="\tlocation /redirect_me {\n\t\treturn 301 \@scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"

sudo apt-get -y update
sudo apt-get install -y nginx
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "[$find][$replace301]" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
