#!/usr/bin/env bash
# configure lb-01 server

config_frontend="\nfrontend main\n\tbind *:80\n\tmode http\n\tmode http\n\tdefault_backend web_servers\n"
config_backend="\nbackend web_servers\n\tbalance roundrobin\n\toption forwardfor\n\tserver 4922-web-01 3.87.86.219:80 check\n\tserver 4922 -web-02 54.227.1.143:80 check\n"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo ENABLED=1 | sudo tee -a /etc/default/haproxy
echo -e "$config_frontend""$config_backend" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
