#!/usr/bin/env bash
#Task 0: Installs ufw firewall

sudo apt-get update -y
sudo apt install ufw -y

sudo ufw default allow outgoing
sudo ufw default deny incoming

sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

sudo ufw enable
